// <autogenerated />
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using MudBlazor;
using PeopleExercise.Web.Models;
using PeopleExercise.Web.Services;
using System.Globalization;
using System.Runtime.CompilerServices;
using PeopleExercise.Web.Funzioni;


namespace PeopleExercise.Web.Components.Pages
{
    public partial class People : IDisposable
    {
        private readonly List<Persona> _people = [];
        
        private IReadOnlyList<PersonPropertyMetadata> _displayProperties = Array.Empty<PersonPropertyMetadata>();
        private IReadOnlyList<PersonPropertyMetadata> _visibleProperties = Array.Empty<PersonPropertyMetadata>();

        private Persona _currentPerson = new();
        private EditContext? _editContext;
   
        private bool _isCreating = true;
        private bool _isEditorVisible;
        private bool _isLoading;
        private const int MaxComuniSuggestions = 50;
        private IReadOnlyList<string> _nomiComuni = Array.Empty<string>();
        private IReadOnlyDictionary<string, string> _comuniByName = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        protected override async Task OnInitializedAsync()
        {
            var properties = PersonSchemaService.GetPersonProperties();

            // Filtriamo subito escludendo l'Id
            var filteredProperties = properties
                .Where(p => p.IsVisible && p.PropertyInfo.Name != nameof(Persona.Id))
                .ToArray();

            // Assegniamo la lista PULITA a entrambe
            _displayProperties = filteredProperties;
            _visibleProperties = filteredProperties;

            await LoadComuniAsync();
            await LoadPeopleAsync();
        }

        private async Task LoadComuniAsync()
        {
            try
            {
                _comuniByName = await ComuniStorageService.GetComuniAsync();
                _nomiComuni = _comuniByName.Keys
                    .OrderBy(nomeComune => nomeComune, StringComparer.OrdinalIgnoreCase)
                    .ToArray();
            }
            catch (Exception)
            {
                _comuniByName = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                _nomiComuni = Array.Empty<string>();
                Snackbar.Add("Impossibile caricare la lista comuni.", Severity.Warning);
            }
        }

        private async Task LoadPeopleAsync()
        {
            _isLoading = true;

            try
            {
                var loadedPeople = await PersonStorageService.GetAllAsync();
                _people.Clear();
                _people.AddRange(loadedPeople.OrderBy(person => person.Nome, StringComparer.OrdinalIgnoreCase));

                ShowPendingWarnings();
            }
            catch (PersonStorageException storageException)
            {
                Snackbar.Add(storageException.UserMessage, Severity.Error);
            }
            finally
            {
                _isLoading = false;
            }
        }

        private void StartCreate()
        {
            _isCreating = true;
            _currentPerson = new Persona();
            ConfigureEditContext(new EditContext(_currentPerson));
            _isEditorVisible = true;
        }

        private void StartEdit(Persona person)
        {
            _isCreating = false;
            _currentPerson = ClonePerson(person);
            ConfigureEditContext(new EditContext(_currentPerson));
            _isEditorVisible = true;
        }

        private void CancelEdit()
        {
            _isEditorVisible = false;
        }

        private async Task SaveCurrentAsync()
        {
            try
            {
                // Sincronizziamo l'ID col codice fiscale prima del salvataggio
                if (!string.IsNullOrWhiteSpace(_currentPerson.codiceFiscale))
                {
                    _currentPerson.Id = _currentPerson.codiceFiscale;
                }

                await PersonStorageService.SaveAsync(_currentPerson);
                Snackbar.Add("Persona salvata correttamente.", Severity.Success);
                _isEditorVisible = false;
                await LoadPeopleAsync();
            }
            catch (Exception ex)
            {
                Snackbar.Add("Errore durante il salvataggio.", Severity.Error);
            }
        }

        private Task OnInvalidSubmit(EditContext editContext)
        {
            StateHasChanged();
            return Task.CompletedTask;
        }

        private async Task OnDeleteClickedAsync(Persona person)
        {
            //await LogToBrowserConsoleAsync($"[People/Delete] click -> Nome='{person.Nome}', Id='{person.Id}'");
            await DeleteAsync(person);
        }

        private async Task OnOpenFileClickedAsync(Persona person)
        {
            //await LogToBrowserConsoleAsync($"[People/Delete] click -> Nome='{person.Nome}', Id='{person.Id}'");
            await OpenPath(person);
        }


        private async Task OpenPath(Persona person)
        {
            try
            {
                await PersonStorageService.OpenFilePath(person.Id);
            }
            catch (PersonStorageException storageException)
            {
                Snackbar.Add(storageException.UserMessage, Severity.Error);
            }
        }


        private async Task DeleteAsync(Persona person)
        {
            //await LogToBrowserConsoleAsync($"[People/Delete] DeleteAsync START -> Id='{person.Id}'");

            var confirmed = await DialogService.ShowMessageBox(
                title: "Conferma eliminazione",
                markupMessage: new Microsoft.AspNetCore.Components.MarkupString($"Vuoi eliminare '{person.Nome}'?"),
                yesText: "Elimina",
                cancelText: "Annulla");

            if (confirmed != true)
            {
                //await LogToBrowserConsoleAsync($"[People/Delete] annullato da dialog -> Id='{person.Id}'");
                return;
            }

            try
            {
                await PersonStorageService.DeleteAsync(person.Id);
                Snackbar.Add("Persona eliminata.", Severity.Success);
                //await LogToBrowserConsoleAsync($"[People/Delete] delete completato -> Id='{person.Id}'");

                await LoadPeopleAsync();
            }
            catch (PersonStorageException storageException)
            {
                //await LogToBrowserConsoleAsync($"[People/Delete] errore storage -> Id='{person.Id}', msg='{storageException.UserMessage}'");
                Snackbar.Add(storageException.UserMessage, Severity.Error);
            }
        }

        private async Task LogToBrowserConsoleAsync(string message)
        {
            try
            {
                await JSRuntime.InvokeVoidAsync("console.log", message);
            }
            catch (JSException)
            {
                // Ignorato: il logging JS non deve bloccare il flusso applicativo.
            }
        }

        private void ShowPendingWarnings()
        {
            foreach (var warningMessage in UserNotificationStore.DrainWarnings())
            {
                Snackbar.Add(warningMessage, Severity.Warning);
            }
        }

        private static string GetDisplayValue(Persona person, PersonPropertyMetadata propertyMetadata)
        {
            var rawValue = propertyMetadata.PropertyInfo.GetValue(person);

            if (rawValue is null)
            {
                return string.Empty;
            }

            if (rawValue is DateTime dateTimeValue)
            {
                return dateTimeValue.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
            }

            if (rawValue is decimal decimalValue)
            {
                return decimalValue.ToString("0.##", CultureInfo.InvariantCulture);
            }

            if (rawValue is bool boolValue)
            {
                return boolValue ? "Si" : "No";
            }

            return rawValue.ToString() ?? string.Empty;
        }

        private static Persona ClonePerson(Persona source)
        {
            var cloned = new Persona();

            foreach (var propertyInfo in typeof(Persona).GetProperties().Where(property => property.CanRead && property.CanWrite))
            {
                propertyInfo.SetValue(cloned, propertyInfo.GetValue(source));
            }

            return cloned;
        }

        private Task CalcoloCodiceFiscale(Persona persona)
        {
            if (!TryBuildCodiceFiscale(persona, out var codiceFiscale))
            {
                Snackbar.Add("Comune non trovato nel file comuni.", Severity.Warning);
                return Task.CompletedTask;
            }

            persona.codiceFiscale = codiceFiscale;
            return Task.CompletedTask;
        }

        private async Task OnDatiCambiati()
        {
            if (!CanAutoCompileCodiceFiscale())
            {
                if (!string.IsNullOrWhiteSpace(_currentPerson.codiceFiscale))
                {
                    _currentPerson.codiceFiscale = string.Empty;
                    _editContext?.NotifyFieldChanged(new FieldIdentifier(_currentPerson, nameof(Persona.codiceFiscale)));
                }
                return;
            }

            if (TryBuildCodiceFiscale(_currentPerson, out var codiceFiscale) &&
                !string.Equals(_currentPerson.codiceFiscale, codiceFiscale, StringComparison.Ordinal))
            {
                _currentPerson.codiceFiscale = codiceFiscale;
                _editContext?.NotifyFieldChanged(new FieldIdentifier(_currentPerson, nameof(Persona.codiceFiscale)));
            }

            await InvokeAsync(StateHasChanged);
        }

        private Task<IEnumerable<string>> SearchComuniAsync(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                IEnumerable<string> defaultResults = _nomiComuni.Take(MaxComuniSuggestions);
                return Task.FromResult(defaultResults);
            }

            IEnumerable<string> filteredResults = _nomiComuni
                .Where(nome => nome.Contains(value, StringComparison.OrdinalIgnoreCase))
                .Take(MaxComuniSuggestions);

            return Task.FromResult(filteredResults);
        }

        private bool HasFieldErrors(string propertyName)
        {
            if (_editContext is null)
            {
                return false;
            }

            var fieldIdentifier = new FieldIdentifier(_currentPerson, propertyName);
            return _editContext.GetValidationMessages(fieldIdentifier).Any();
        }

        private string? GetFirstFieldError(string propertyName)
        {
            if (_editContext is null)
            {
                return null;
            }

            var fieldIdentifier = new FieldIdentifier(_currentPerson, propertyName);
            return _editContext.GetValidationMessages(fieldIdentifier).FirstOrDefault();
        }

        private Task OnLuogoDiNascitaChanged(string? value)
        {
            _currentPerson.LuogoDiNascita = (value ?? string.Empty).Trim();
            _editContext?.NotifyFieldChanged(new FieldIdentifier(_currentPerson, nameof(Persona.LuogoDiNascita)));
            return Task.CompletedTask;
        }

        // -> data: 2026-03-17
        private bool CanAutoCompileCodiceFiscale()
        {
            if (_editContext is null)
            {
                return false;
            }

            if (string.IsNullOrWhiteSpace(_currentPerson.Nome) ||
                string.IsNullOrWhiteSpace(_currentPerson.Cognome) ||
                string.IsNullOrWhiteSpace(_currentPerson.sesso) ||
                string.IsNullOrWhiteSpace(_currentPerson.LuogoDiNascita) ||
                !_currentPerson.DataNascita.HasValue)
            {
                return false;
            }

            var sessoNormalized = _currentPerson.sesso.Trim().ToUpperInvariant();
            if (sessoNormalized is not "M" and not "F")
            {
                return false;
            }

            var luogo = _currentPerson.LuogoDiNascita.Trim();

            if (!_comuniByName.ContainsKey(luogo))
            {
                return false;
            }

            return !HasFieldErrors(nameof(Persona.Nome)) &&
                   !HasFieldErrors(nameof(Persona.Cognome)) &&
                   !HasFieldErrors(nameof(Persona.sesso)) &&
                   !HasFieldErrors(nameof(Persona.LuogoDiNascita)) &&
                   !HasFieldErrors(nameof(Persona.DataNascita));
        }

        // -> data: 2026-03-17
        // -> data: 2026-03-17
        private bool TryBuildCodiceFiscale(Persona persona, out string codiceFiscale)
        {
            codiceFiscale = string.Empty;

            if (persona is null)
            {
                return false;
            }

            if (string.IsNullOrWhiteSpace(persona.Nome) ||
                string.IsNullOrWhiteSpace(persona.Cognome) ||
                string.IsNullOrWhiteSpace(persona.sesso) ||
                string.IsNullOrWhiteSpace(persona.LuogoDiNascita) ||
                !persona.DataNascita.HasValue)
            {
                return false;
            }

            var luogo = persona.LuogoDiNascita.Trim();

            if (!_comuniByName.TryGetValue(luogo, out var codiceComune))
            {
                return false;
            }

            var sessoNormalizzato = persona.sesso.Trim().ToUpperInvariant();

            if (sessoNormalizzato is not "M" and not "F")
            {
                return false;
            }

            try
            {
                var utility = new Utility();

                string parzialeNome = utility.calcoloNomeCognomeCodFiscale(persona.Nome, true);
                string parzialeCognome = utility.calcoloNomeCognomeCodFiscale(persona.Cognome, false);
                string parzialeData = utility.CalcolaDataSesso(persona.DataNascita.Value, sessoNormalizzato);

                string parziale = (parzialeCognome + parzialeNome + parzialeData + codiceComune).ToUpperInvariant();

                if (parziale.Length != 15)
                {
                    return false;
                }

                string controllo = utility.CalcolaCarattereControllo(parziale);
                codiceFiscale = parziale + controllo;
                return true;
            }
            catch
            {
                return false;
            }
        }

        private void ConfigureEditContext(EditContext editContext)
        {
            if (_editContext is not null)
            {
                _editContext.OnFieldChanged -= HandleEditContextFieldChanged;
            }

            _editContext = editContext;
            _editContext.OnFieldChanged += HandleEditContextFieldChanged;
        }

        private void HandleEditContextFieldChanged(object? sender, FieldChangedEventArgs fieldChangedEventArgs)
        {
            if (fieldChangedEventArgs.FieldIdentifier.FieldName == nameof(Persona.codiceFiscale))
            {
                return;
            }

            _ = InvokeAsync(OnDatiCambiati);
        }

        public void Dispose()
        {
            if (_editContext is not null)
            {
                _editContext.OnFieldChanged -= HandleEditContextFieldChanged;
            }
        }


    }
}
    


